version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
        - '8080:80'
    volumes:
        - ./config/nginx:/etc/nginx/conf.d
        - ./data/wordpress:/var/www/html

  wordpress:
    image: alwynpan/docker-wordpress:6.2.2-php7.4-fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      PHP_MEMORY_LIMIT: 128M
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
      PHP_MAX_EXECUTION_TIME: 600
    volumes:
      - ./data/wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
