FROM wordpress:5.9.2-php7.3-fpm-alpine

ENV PHP_MEMORY_LIMIT 128M
ENV PHP_UPLOAD_MAX_FILESIZE 10M
ENV PHP_POST_MAX_SIZE 10M
ENV PHP_MAX_EXECUTION_TIME 120

COPY ["entrypoint.sh", "/"]

RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]

CMD ["php-fpm"]
